<?php
session_start();
	if(isset($_POST['logout'])){
		if(isset($_SESSION['username'])){
		unset($_SESSION['username']);
	}if(isset($_SESSION['admin'])){
		unset($_SESSION['admin']);
	}
		header('location:http://localhost/tuyensinh/admin/form_login.php');
	}
?>